### ISSUE TITLE
error line  12 on compilertest.cpp

### ISSUE THREAD

**Issue by seyyedmohammadmodarresi** [KambizAsadzadeh/Project-Template#4]
/Project-Template/source/examples/compilertest.cpp:12: error: invalid operands of types ‘int’ and ‘<unresolved overloaded function type>’ to binary ‘operator<<’
/Project-Template/source/examples/compilertest.cpp: In member function ‘void CompilerTest::getCompilerInfo() const’:
/media/smm/09103373496/mohammad/official/programing/cppandqt/cppeducation/example/template/Project-Template/source/examples/compilertest.cpp:12:49: error: invalid operands of types ‘int’ and ‘<unresolved overloaded function type>’ to binary ‘operator<<’
   12 |   cout << "Compiler Version : " << COMPILER_VER << endl;

**Comment by KambizAsadzadeh** [comment]
> 
Can you tell me which compiler you are using?

**Comment by seyyedmohammadmodarresi** [comment]
Gcc
